#!/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright (c) 1994, 2010, Oracle and/or its affiliates. All rights reserved.
#
# Copyright (c) 1984, 1986, 1987, 1988, 1989 AT&T.
# All rights reserved.
#

# This file loads keyboard mappings and initializes keyboard defaults

. /lib/svc/share/smf_include.sh

smf_is_globalzone || exit $SMF_EXIT_OK

set_keymap_prop()
{
	val="$3"

	[ -z "$val" ] && return 0

	if [ "$type" = "boolean" ]; then
		[ "$val" = "on" ] && val="true"
		[ "$val" = "off" ] && val="false"
	fi

	/usr/sbin/svccfg -s $SMF_FMRI setprop keymap/$1 = $2: "$val"
}

#
# Systems with no hardware keyboard ID may provide an eeprom value,
# or the value can be supplied in svc:/system/keymap:default. A value
# supplied in svc:/system/keymap:default will override the value
# supplied in eeprom.
#
[ -x /usr/lib/set_keyboard_layout ] && /usr/lib/set_keyboard_layout

# Import legacy keyboard configuration

/usr/bin/svcprop -q -c -p keymap/imported $SMF_FMRI
if [ $? -ne 0 ]; then
	if [ -r /etc/default/kbd ]; then
		. /etc/default/kbd
		set_keymap_prop keyboard_abort astring "$KEYBOARD_ABORT"
		set_keymap_prop keyclick boolean "$KEYCLICK"
		set_keymap_prop repeat_delay integer "$REPEAT_DELAY"
		set_keymap_prop repeat_rate integer "$REPEAT_RATE"
		set_keymap_prop layout astring "$LAYOUT"
		set_keymap_prop kbd_beeper_freq integer "$KBD_BEEPER_FREQ"
		set_keymap_prop console_beeper_freq integer \
			"$CONSOLE_BEEPER_FREQ"
	fi
	set_keymap_prop imported boolean true
	/usr/sbin/svccfg -s $SMF_FMRI refresh
fi

# Initialize the keyboard defaults

[ -h /dev/kbd -a -x /usr/bin/kbd ] && /usr/bin/kbd -i >/dev/null 2>&1

# Load the keymap for the attached keyboard.
/usr/bin/loadkeys
